package com.inspius.yo_video.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.inspius.yo_video.greendao.DBWishListVideo;
import com.inspius.yo_video.greendao.DBRecentVideo;
import com.inspius.yo_video.greendao.DBKeywordSearch;
import com.inspius.yo_video.greendao.DBNotification;
import com.inspius.yo_video.greendao.DBVideoDownload;

import com.inspius.yo_video.greendao.DBWishListVideoDao;
import com.inspius.yo_video.greendao.DBRecentVideoDao;
import com.inspius.yo_video.greendao.DBKeywordSearchDao;
import com.inspius.yo_video.greendao.DBNotificationDao;
import com.inspius.yo_video.greendao.DBVideoDownloadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBWishListVideoDaoConfig;
    private final DaoConfig dBRecentVideoDaoConfig;
    private final DaoConfig dBKeywordSearchDaoConfig;
    private final DaoConfig dBNotificationDaoConfig;
    private final DaoConfig dBVideoDownloadDaoConfig;

    private final DBWishListVideoDao dBWishListVideoDao;
    private final DBRecentVideoDao dBRecentVideoDao;
    private final DBKeywordSearchDao dBKeywordSearchDao;
    private final DBNotificationDao dBNotificationDao;
    private final DBVideoDownloadDao dBVideoDownloadDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBWishListVideoDaoConfig = daoConfigMap.get(DBWishListVideoDao.class).clone();
        dBWishListVideoDaoConfig.initIdentityScope(type);

        dBRecentVideoDaoConfig = daoConfigMap.get(DBRecentVideoDao.class).clone();
        dBRecentVideoDaoConfig.initIdentityScope(type);

        dBKeywordSearchDaoConfig = daoConfigMap.get(DBKeywordSearchDao.class).clone();
        dBKeywordSearchDaoConfig.initIdentityScope(type);

        dBNotificationDaoConfig = daoConfigMap.get(DBNotificationDao.class).clone();
        dBNotificationDaoConfig.initIdentityScope(type);

        dBVideoDownloadDaoConfig = daoConfigMap.get(DBVideoDownloadDao.class).clone();
        dBVideoDownloadDaoConfig.initIdentityScope(type);

        dBWishListVideoDao = new DBWishListVideoDao(dBWishListVideoDaoConfig, this);
        dBRecentVideoDao = new DBRecentVideoDao(dBRecentVideoDaoConfig, this);
        dBKeywordSearchDao = new DBKeywordSearchDao(dBKeywordSearchDaoConfig, this);
        dBNotificationDao = new DBNotificationDao(dBNotificationDaoConfig, this);
        dBVideoDownloadDao = new DBVideoDownloadDao(dBVideoDownloadDaoConfig, this);

        registerDao(DBWishListVideo.class, dBWishListVideoDao);
        registerDao(DBRecentVideo.class, dBRecentVideoDao);
        registerDao(DBKeywordSearch.class, dBKeywordSearchDao);
        registerDao(DBNotification.class, dBNotificationDao);
        registerDao(DBVideoDownload.class, dBVideoDownloadDao);
    }
    
    public void clear() {
        dBWishListVideoDaoConfig.getIdentityScope().clear();
        dBRecentVideoDaoConfig.getIdentityScope().clear();
        dBKeywordSearchDaoConfig.getIdentityScope().clear();
        dBNotificationDaoConfig.getIdentityScope().clear();
        dBVideoDownloadDaoConfig.getIdentityScope().clear();
    }

    public DBWishListVideoDao getDBWishListVideoDao() {
        return dBWishListVideoDao;
    }

    public DBRecentVideoDao getDBRecentVideoDao() {
        return dBRecentVideoDao;
    }

    public DBKeywordSearchDao getDBKeywordSearchDao() {
        return dBKeywordSearchDao;
    }

    public DBNotificationDao getDBNotificationDao() {
        return dBNotificationDao;
    }

    public DBVideoDownloadDao getDBVideoDownloadDao() {
        return dBVideoDownloadDao;
    }

}
