package com.inspius.yo_video.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBKEYWORD_SEARCH".
 */
public class DBKeywordSearch {

    private Long id;
    /** Not-null value. */
    private String keyword;

    public DBKeywordSearch() {
    }

    public DBKeywordSearch(Long id) {
        this.id = id;
    }

    public DBKeywordSearch(Long id, String keyword) {
        this.id = id;
        this.keyword = keyword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKeyword() {
        return keyword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

}
