package com.inspius.yo_video.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBNOTIFICATION".
 */
public class DBNotification {

    private Long id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String message;
    /** Not-null value. */
    private String content;
    private int status;

    public DBNotification() {
    }

    public DBNotification(Long id) {
        this.id = id;
    }

    public DBNotification(Long id, String title, String message, String content, int status) {
        this.id = id;
        this.title = title;
        this.message = message;
        this.content = content;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getMessage() {
        return message;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMessage(String message) {
        this.message = message;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

}
