package com.inspius.canyon.yo_video.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.inspius.canyon.yo_video.greendao.NewWishList;
import com.inspius.canyon.yo_video.greendao.RecentVideos;
import com.inspius.canyon.yo_video.greendao.DBKeywordSearch;
import com.inspius.canyon.yo_video.greendao.DBNotification;

import com.inspius.canyon.yo_video.greendao.NewWishListDao;
import com.inspius.canyon.yo_video.greendao.RecentVideosDao;
import com.inspius.canyon.yo_video.greendao.DBKeywordSearchDao;
import com.inspius.canyon.yo_video.greendao.DBNotificationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newWishListDaoConfig;
    private final DaoConfig recentVideosDaoConfig;
    private final DaoConfig dBKeywordSearchDaoConfig;
    private final DaoConfig dBNotificationDaoConfig;

    private final NewWishListDao newWishListDao;
    private final RecentVideosDao recentVideosDao;
    private final DBKeywordSearchDao dBKeywordSearchDao;
    private final DBNotificationDao dBNotificationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newWishListDaoConfig = daoConfigMap.get(NewWishListDao.class).clone();
        newWishListDaoConfig.initIdentityScope(type);

        recentVideosDaoConfig = daoConfigMap.get(RecentVideosDao.class).clone();
        recentVideosDaoConfig.initIdentityScope(type);

        dBKeywordSearchDaoConfig = daoConfigMap.get(DBKeywordSearchDao.class).clone();
        dBKeywordSearchDaoConfig.initIdentityScope(type);

        dBNotificationDaoConfig = daoConfigMap.get(DBNotificationDao.class).clone();
        dBNotificationDaoConfig.initIdentityScope(type);

        newWishListDao = new NewWishListDao(newWishListDaoConfig, this);
        recentVideosDao = new RecentVideosDao(recentVideosDaoConfig, this);
        dBKeywordSearchDao = new DBKeywordSearchDao(dBKeywordSearchDaoConfig, this);
        dBNotificationDao = new DBNotificationDao(dBNotificationDaoConfig, this);

        registerDao(NewWishList.class, newWishListDao);
        registerDao(RecentVideos.class, recentVideosDao);
        registerDao(DBKeywordSearch.class, dBKeywordSearchDao);
        registerDao(DBNotification.class, dBNotificationDao);
    }
    
    public void clear() {
        newWishListDaoConfig.getIdentityScope().clear();
        recentVideosDaoConfig.getIdentityScope().clear();
        dBKeywordSearchDaoConfig.getIdentityScope().clear();
        dBNotificationDaoConfig.getIdentityScope().clear();
    }

    public NewWishListDao getNewWishListDao() {
        return newWishListDao;
    }

    public RecentVideosDao getRecentVideosDao() {
        return recentVideosDao;
    }

    public DBKeywordSearchDao getDBKeywordSearchDao() {
        return dBKeywordSearchDao;
    }

    public DBNotificationDao getDBNotificationDao() {
        return dBNotificationDao;
    }

}
