package com.inspius.canyon.yo_video.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBRECENT_VIDEO".
 */
public class DBRecentVideo {

    private Long id;
    private int videoId;
    /** Not-null value. */
    private String category;
    /** Not-null value. */
    private String series;
    /** Not-null value. */
    private String view;
    /** Not-null value. */
    private String image;
    /** Not-null value. */
    private String link;
    /** Not-null value. */
    private String name;
    private int userID;

    public DBRecentVideo() {
    }

    public DBRecentVideo(Long id) {
        this.id = id;
    }

    public DBRecentVideo(Long id, int videoId, String category, String series, String view, String image, String link, String name, int userID) {
        this.id = id;
        this.videoId = videoId;
        this.category = category;
        this.series = series;
        this.view = view;
        this.image = image;
        this.link = link;
        this.name = name;
        this.userID = userID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVideoId() {
        return videoId;
    }

    public void setVideoId(int videoId) {
        this.videoId = videoId;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    /** Not-null value. */
    public String getSeries() {
        return series;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSeries(String series) {
        this.series = series;
    }

    /** Not-null value. */
    public String getView() {
        return view;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setView(String view) {
        this.view = view;
    }

    /** Not-null value. */
    public String getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(String image) {
        this.image = image;
    }

    /** Not-null value. */
    public String getLink() {
        return link;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLink(String link) {
        this.link = link;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getUserID() {
        return userID;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

}
