package com.inspius.canyon.yo_video.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBVIDEO_DOWNLOAD".
 */
public class DBVideoDownload {

    private Long id;
    private int videoId;
    /** Not-null value. */
    private String path;
    /** Not-null value. */
    private String title;

    public DBVideoDownload() {
    }

    public DBVideoDownload(Long id) {
        this.id = id;
    }

    public DBVideoDownload(Long id, int videoId, String path, String title) {
        this.id = id;
        this.videoId = videoId;
        this.path = path;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVideoId() {
        return videoId;
    }

    public void setVideoId(int videoId) {
        this.videoId = videoId;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

}
